### ISSUE TITLE
Make the Python script compatible with Python 2.7 and Python 3.

### ISSUE THREAD

**Issue by aaronbieber** [aaronbieber/org-protocol-handler#6]
On both my home and work Macs, `python` runs Python 2.7. I'm not sure when that may have changed to 3, but certainly some enterprising folks may have Python 3 installed as their default Python version.

Make sure this script can run in both Python versions. It appears that `six` is installed in macOS by default so that may be an option. The main difference, I think, is that `urllib` reorganized and some of the package names are different in Python 3.

**Comment by andrewsanchez** [comment]
That will be great not to have to fuss around with `main.scpt`.  See https://github.com/aaronbieber/org-protocol-handler/pull/7.
